export declare const COLORS: {
    base: string;
    baseLight: string;
    baseDark: string;
    baseBorder: string;
    blue: string;
    green: string;
    dark_green: string;
    red: string;
    dark_red: string;
    orange: string;
    dark_orange: string;
    text_dark: string;
    text: string;
    text_light: string;
    background: string;
    card_background: string;
    light_gray: string;
    medium_gray: string;
    dark_gray: string;
};
